### PR TITLE
Added additional package methods, useful for unit testing

### PR DESCRIPTION
**Pull request by david-driscoll**

### CODE REVIEW

**Comment by unional** [comment]
Thank!.

I'm not sure can we use the build-in promise in this case since atom is an environment.

@blakeembrey  what do you think? Should we also use `es6-promise` here?

**Comment by blakeembrey** [comment]
I think it's probably fine to do. Promise is global in Atom since it's a later V8 version.

**Comment by blakeembrey** [comment]
This could actually even use `Promise` instead of `PromiseLike`, right?

**Comment by unional** [comment]
I think it is safer to use `PromiseLike`?

**Comment by blakeembrey** [comment]
Not really, why? It's a return type, so it's likely you'd want a full promise class instead of `PromiseLike`.

**Pull request merged**
